workflows:
  ios_prepare:
    name: iOS Prepare (no signing)
    working_directory: frontend
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: com.cuentaclara.app
        BUILD_NAME: 1.0.0
        BUILD_NUMBER: 1
        API_BASE_URL: https://cuentaclara-production.up.railway.app
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - build
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get
      - name: Pod install (iOS)
        script: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Build iOS (no code signing)
        script: |
          # Solo compila el .app para verificar integridad. NO archiva.
          flutter build ios --release --no-codesign \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER \
            --dart-define=API_BASE_URL=$API_BASE_URL
    artifacts:
      - build/ios/iphoneos/*.app

  ios_testflight:
    name: iOS Release → TestFlight (signed)
    working_directory: frontend
    max_build_duration: 90
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: com.cuentaclara.app
        BUILD_NAME: 1.0.0
        BUILD_NUMBER: 1
        API_BASE_URL: https://cuentaclara-production.up.railway.app
        TEAM_ID: XQJ843FZ7Q
      # Si NO vas a usar "Integrations", definí estas 3 variables en Environment variables:
      # APP_STORE_CONNECT_PRIVATE_KEY  (contenido completo del .p8, incluyendo BEGIN/END)
      # APP_STORE_CONNECT_KEY_IDENTIFIER (ej: 1A2BC3D4EF)
      # APP_STORE_CONNECT_ISSUER_ID      (UUID)
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - build

    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      - name: Install pods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Prepare automatic signing (fetch certs & profiles)
        script: |
          # 1) Keychain y credenciales
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"
          keychain add-certificates

          # 2) Aplicar perfiles al proyecto (ajusta PROVISIONING_PROFILE_SPECIFIER por target/CONFIG)
          xcode-project use-profiles --project ios/Runner.xcodeproj --scheme Runner

          echo "== Perfiles disponibles =="
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles || true

      - name: Build & Sign IPA (Xcode)
        script: |
          # Usamos herramienta de Codemagic que envuelve xcodebuild con export correcto para App Store
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --archive-method app-store \
            --team-id $TEAM_ID

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        # Publica a TestFlight usando las mismas credenciales de arriba
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        # beta_groups:
        #   - Internal Testers
