#
# Codemagic CI/CD para la aplicación cuentaclara
#

workflows:
  ios_prepare:
    name: iOS Prepare (no signing)
    working_directory: frontend
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: com.cuentaclara.app
        BUILD_NAME: 1.0.0
        BUILD_NUMBER: 1
        API_BASE_URL: https://cuentaclara-production.up.railway.app
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - build
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      - name: Install pods (iOS)
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS (no code signing)
        script: |
          flutter build ios --release --no-codesign \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER \
            --dart-define=API_BASE_URL=$API_BASE_URL

    artifacts:
      - build/ios/iphoneos/*.app

  ios_testflight:
    name: iOS Release → TestFlight (signed)
    working_directory: frontend
    max_build_duration: 90
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_connect
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cuentaclara.app
      vars:
        BUNDLE_ID: com.cuentaclara.app
        BUILD_NAME: 1.0.0
        BUILD_NUMBER: 1
        API_BASE_URL: https://cuentaclara-production.up.railway.app
        TEAM_ID: XQJ843FZ7Q

    cache:
      cache_path_
