#
# Codemagic CI/CD para la aplicación cuentaclara
#

workflows:
  ios_prepare:
    name: iOS Prepare (no signing)
    working_directory: frontend
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: com.cuentaclara.app
        BUILD_NAME: 1.0.0
        BUILD_NUMBER: 1
        API_BASE_URL: https://cuentaclara-production.up.railway.app
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - build
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      - name: Install pods (iOS)
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS (no code signing)
        script: |
          flutter build ios --release --no-codesign \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER \
            --dart-define=API_BASE_URL=$API_BASE_URL

    artifacts:
      - build/ios/iphoneos/*.app

  ios_testflight:
    name: iOS Release → TestFlight (signed)
    working_directory: frontend
    max_build_duration: 90
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_connect
      vars:
        BUNDLE_ID: com.cuentaclara.app
        BUILD_NAME: 1.0.0
        BUILD_NUMBER: 1
        API_BASE_URL: https://cuentaclara-production.up.railway.app
        TEAM_ID: XQJ843FZ7Q

    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - build

    scripts:
      - name: Setup Keychain and Certificates 🔑
        script: |
          keychain initialize
          keychain add-certificates

      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      - name: Install pods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: "Code Signing: Get Profile (Step 1)"
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE --create

      - name: "Create export_options.plist (Step 2)"
        script: |
          PROF_PATH="$(ls ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision | head -n 1)"
          if [ -z "$PROF_PATH" ]; then
            echo "No provisioning profiles found after fetch-signing-files"
            exit 1
          fi

          PROFILE_NAME="$(security cms -D -i "$PROF_PATH" | /usr/libexec/PlistBuddy -c 'Print :Name' /dev/stdin)"

          cat > /Users/builder/export_options.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>compileBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>destination</key>
            <string>export</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>__BUNDLE_ID__</key>
              <string>__PROFILE_NAME__</string>
            </dict>
          </dict>
          </plist>
          EOF

          /usr/bin/sed -i "" "s#__BUNDLE_ID__#${BUNDLE_ID}#g" /Users/builder/export_options.plist
          /usr/bin/sed -i "" "s#__PROFILE_NAME__#${PROFILE_NAME}#g" /Users/builder/export_options.plist

      - name: "Build & Sign IPA (Step 3)"
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --export-options-plist /Users/builder/export_options.plist

      - name: Imprimir info IPA (opcional)
        script: |
          xcode-project ipa-info build/ios/ipa/*.ipa || true

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
