#
# Codemagic CI/CD para la aplicación cuentaclara
#

workflows:
  ios_prepare:
    name: iOS Prepare (no signing)
    working_directory: frontend
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: com.cuentaclara.app
        BUILD_NAME: 1.0.0
        BUILD_NUMBER: 1
        API_BASE_URL: https://cuentaclara-production.up.railway.app
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - build
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      - name: Install pods (iOS)
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS (no code signing)
        script: |
          flutter build ios --release --no-codesign \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER \
            --dart-define=API_BASE_URL=$API_BASE_URL

    artifacts:
      - build/ios/iphoneos/*.app

  ios_testflight:
    name: iOS Release → TestFlight (signed)
    working_directory: frontend
    max_build_duration: 90

    # 👇 AGREGADO: decirle a Codemagic qué integración de App Store Connect usar
    integrations:
      app_store_connect: CuentaClara API Key  # <-- reemplazá este texto por el NOMBRE exacto de tu integración en Codemagic

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_connect
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cuentaclara.app
      vars:
        BUNDLE_ID: com.cuentaclara.app
        BUILD_NAME: 1.0.0
        BUILD_NUMBER: 1
        API_BASE_URL: https://cuentaclara-production.up.railway.app
        TEAM_ID: XQJ843FZ7Q

    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - build

    scripts:
      # 1) Inicializar keychain
      - name: Setup Keychain 🔑
        script: |
          keychain initialize

      # 2) Flutter clean & pub get
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      # 3) Instalar pods
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      # 4) Aplicar certificados y provisioning profiles subidos a Codemagic
      - name: Aplicar perfiles de firma (use-profiles)
        script: |
          xcode-project use-profiles --export-options-plist "$HOME/export_options.plist"

      # 5) Build del IPA firmado
      - name: Build IPA firmado
        script: |
          flutter build ipa --release \
            --export-options-plist="$HOME/export_options.plist" \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER \
            --dart-define=API_BASE_URL=$API_BASE_URL

      # 6) Info del IPA (opcional)
      - name: Imprimir info IPA (opcional)
        script: |
          xcode-project ipa-info build/ios/ipa/*.ipa || true

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
