workflows:
  ios_prepare:
    name: iOS Prepare (no signing)
    working_directory: frontend
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: com.cuentaclara.app
        BUILD_NAME: 1.0.0
        BUILD_NUMBER: 1
        API_BASE_URL: https://cuentaclara-production.up.railway.app
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - build
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get
      - name: Pod install (iOS)
        script: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Build iOS (no code signing)
        script: |
          flutter build ios --release --no-codesign \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER \
            --dart-define=API_BASE_URL=$API_BASE_URL
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/archive/*.xcarchive

  ios_testflight:
    name: iOS Release → TestFlight
    working_directory: frontend
    max_build_duration: 90
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: com.cuentaclara.app
        BUILD_NAME: 1.0.0
        BUILD_NUMBER: 1
        API_BASE_URL: https://cuentaclara-production.up.railway.app
      groups:
        - app_store_connect   # 👈 grupo con las 3 credenciales del Apple API Key (.p8, Key ID, Issuer ID)
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - build
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      - name: Prepare automatic signing (App Store Connect)
        script: |
          # 1) Inicializa el llavero de certificados
          keychain initialize

          # 2) Descarga/crea perfiles y certificados del Apple Developer Portal
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create

          # 3) Agrega los certificados al keychain
          keychain add-certificates

          # 4) Aplica automáticamente los perfiles descargados al proyecto Xcode
          xcode-project use-profiles

      - name: Build IPA (signed)
        script: |
          # 5) Compila y exporta IPA firmado (usa los perfiles aplicados)
          flutter build ipa --release \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER \
            --dart-define=API_BASE_URL=$API_BASE_URL

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        # opcional: definir grupos de testers
        # beta_groups:
        #   - Internal Testers
