"""Add field: is_overdue in Installemt

Revision ID: 145c9e23d8e8
Revises: 5cc6c568423f
Create Date: 2025-05-02 20:20:13.460858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '145c9e23d8e8'
down_revision: Union[str, None] = '5cc6c568423f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installments', sa.Column('is_overdue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installments', 'is_overdue')
    # ### end Alembic commands ###
