"""Add province to customers table

Revision ID: 3775fd3265a0
Revises: 909a84a47aa2
Create Date: 2025-04-30 21:06:31.697622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3775fd3265a0'
down_revision: Union[str, None] = '909a84a47aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column('customers', sa.Column('province', sa.String(length=100), nullable=False, server_default='Tucumán'))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'province')
    # ### end Alembic commands ###
