"""Add status field to Installment model

Revision ID: 442aaa9154bd
Revises: 68491af79242
Create Date: 2025-05-02 12:28:11.590898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442aaa9154bd'
down_revision: Union[str, None] = '68491af79242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installments', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installments', 'status')
    # ### end Alembic commands ###
