"""Change field name: Installment_count in Loan and Purchases

Revision ID: 5cc6c568423f
Revises: 442aaa9154bd
Create Date: 2025-05-02 19:59:09.301039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc6c568423f'
down_revision: Union[str, None] = '442aaa9154bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('installments_count', sa.Integer(), nullable=False))
    op.add_column('purchases', sa.Column('installments_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'installments_count')
    op.drop_column('loans', 'installments_count')
    # ### end Alembic commands ###
