"""fix_created_at_default

Revision ID: 7cc98bdedf7b
Revises: 8fda77b8adb0
Create Date: 2025-05-01 21:39:15.925637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc98bdedf7b'
down_revision: Union[str, None] = '8fda77b8adb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    # ### end Alembic commands ###
