"""Add dni column and change created_at to DateTime

Revision ID: 90027a26ed1d
Revises: 3775fd3265a0
Create Date: 2025-05-01 21:27:26.086121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90027a26ed1d'
down_revision: Union[str, None] = '3775fd3265a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('dni', sa.String(), nullable=True))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_customers_dni'), 'customers', ['dni'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_dni'), table_name='customers')
    op.alter_column('customers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('customers', 'dni')
    # ### end Alembic commands ###
