"""Añadir campos email y password a empleados

Revision ID: 909a84a47aa2
Revises: 91b5f96035eb
Create Date: 2025-04-27 21:43:02.549312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909a84a47aa2'
down_revision: Union[str, None] = '91b5f96035eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('email', sa.String(), nullable=False))
    op.add_column('employees', sa.Column('password', sa.String(), nullable=False))
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_column('employees', 'password')
    op.drop_column('employees', 'email')
    # ### end Alembic commands ###
