"""Agregar company_id a Employee, actualizar Loans, Purchases y demás cambios

Revision ID: 91b5f96035eb
Revises: 255d9432fb12
Create Date: 2025-04-27 20:56:03.810902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b5f96035eb'
down_revision: Union[str, None] = '255d9432fb12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('customers', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'companies', ['company_id'], ['id'])
    op.add_column('employees', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'companies', ['company_id'], ['id'])
    op.add_column('loans', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loans', 'companies', ['company_id'], ['id'])
    op.add_column('purchases', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchases', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'company_id')
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_column('loans', 'company_id')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'company_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'company_id')
    op.drop_table('companies')
    # ### end Alembic commands ###
