"""Add employee_id to customers

Revision ID: d066aba50110
Revises: 2456db19ea9b
Create Date: 2025-04-03 21:23:41.136590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd066aba50110'
down_revision: Union[str, None] = '2456db19ea9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'employee_id')
    # ### end Alembic commands ###
